name: test
on:
  workflow_dispatch: null
  pull_request:
    paths:
      - 'packages/**'
  push:
    branches:
      - 'master'
    paths:
      - 'packages/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  init:
    name: init
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.detect.outputs.packages }}
    steps:
      - uses: actions/checkout@v3
      - id: changes
        name: Check for new or updated files
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b  # v1.2.4
      - id: detect
        name: Detect changed packages
        uses: ./.github/actions/detect-packages

  test:
    if: needs.init.outputs.packages != '[]'
    name: test
    needs:
      - init
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.init.outputs.packages) }}
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - id: sha
        name: Compute sha
        uses: ./.github/actions/compute-sha
        with:
          path: packages/${{ matrix.package }}
      - id: check-cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ matrix.package }}/${{ steps.sha.outputs.sha }}
          lookup-only: true
          path: packages/${{ matrix.package }}/blank.txt
      - name: Install poetry
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
          pip install --upgrade pip
          pip install poetry==1.6.1
      - name: Install dependencies
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
          poetry install
      - name: Run tests
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
          poetry run inv verify
      - name: Create cache dummy
        if: steps.check-cache.outputs.cache-hit != 'true'
        run: |
          touch blank.txt
      - id: save-cache
        if: steps.check-cache.outputs.cache-hit != 'true'
        name: Cache test result
        uses: actions/cache/save@v3
        with:
          key: ${{ matrix.package }}/${{ steps.sha.outputs.sha }}
          path: packages/${{ matrix.package }}/blank.txt
